FROM mcr.microsoft.com/dotnet/core/sdk:3.1
WORKDIR /app

COPY *.cdproj ./
RUN donet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "UserManager.dll"]