version: '3'

services:
  usermanager:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password="pass123"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=\app\cert.pfx
    image: kaisuj/usermanager
    ports:
      - "1005:5001"
      - "1000:5000"
      - "8080:80"
    build:
      context: .
      dockerfile: dockerfile