FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY *.csproj ./
COPY aspnetapp.pfx ./

RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
COPY --from=build-env /app/aspnetapp.pfx /https/
ENTRYPOINT ["dotnet", "UserManager.dll"]

#ENTRYPOINT ["sleep", "5m"]