version: '3'

services:
  usermanager:
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS="https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password="crypticpassword"
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    image: kaisuj/usermanager
    ports:
      - "5001:443"
      - "5000:80"
    build:
      context: .
      dockerfile: dockerfile
    volumes: 
      - E:\\https:/https:ro
      #- C:\\Users\\kaisu\\.aspnet\\https:/https/:rw